"""
analytics.py
============

Analytics page for the Enterprise Network Intrusion Intelligence System
dashboard.

This module renders exploratory data insights and model performance
analytics by reading pre-computed artifacts produced upstream by other
pipeline stages:

    - Dataset insights: reads a processed data sample / summary from
      ``data/processed/`` (produced by Member A's preprocessing and EDA
      modules).
    - Model performance: reads evaluation artifacts from
      ``reports/metrics/`` (produced by Member B's ``evaluate_model.py``),
      such as classification reports, confusion matrices, and ROC data.
    - Static figures: displays any pre-rendered charts saved to
      ``reports/figures/`` by the EDA/plotting modules.

This page performs NO model training or heavy recomputation itself —
it is a read-only visualization layer over artifacts generated by other
modules, keeping the dashboard fast and decoupled from the ML pipeline.

Author: Member C
Python: 3.11
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

try:
    from src.utils.logger import get_logger
except ImportError:  # pragma: no cover - fallback until utils/logger.py exists
    def get_logger(name: str) -> logging.Logger:
        """Fallback logger factory mirroring the shared logging interface."""
        logger = logging.getLogger(name)
        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(
                "%(asctime)s | %(levelname)-8s | %(name)s | %(message)s"
            )
            handler.setFormatter(formatter)
            logger.addHandler(handler)
            logger.setLevel(logging.INFO)
        return logger

try:
    from src.utils.config import PROCESSED_DATA_DIR, REPORTS_DIR
except ImportError:  # pragma: no cover - fallback until utils/config.py exists
    PROCESSED_DATA_DIR = Path("data/processed")
    REPORTS_DIR = Path("reports")

logger = get_logger(__name__)

METRICS_DIR = Path(REPORTS_DIR) / "metrics"
FIGURES_DIR = Path(REPORTS_DIR) / "figures"

CLASSIFICATION_REPORT_PATH = METRICS_DIR / "classification_report.json"
CONFUSION_MATRIX_PATH = METRICS_DIR / "confusion_matrix.csv"
FEATURE_IMPORTANCE_PATH = METRICS_DIR / "feature_importance.csv"
MODEL_COMPARISON_PATH = METRICS_DIR / "model_comparison.csv"

SAMPLE_DATA_PATH = Path(PROCESSED_DATA_DIR) / "sample.csv"
LABEL_COLUMN_CANDIDATES = ["Label", "label", "attack_type", "class"]


# --------------------------------------------------------------------------
# Cached loaders
# --------------------------------------------------------------------------
@st.cache_data(show_spinner="Loading dataset sample...")
def _load_sample_data() -> Optional[pd.DataFrame]:
    """
    Load a lightweight sample of the processed dataset for visualization.

    Returns:
        A DataFrame if the sample file exists and can be parsed,
        otherwise None.
    """
    try:
        if not SAMPLE_DATA_PATH.exists():
            logger.info("Processed data sample not found at %s", SAMPLE_DATA_PATH)
            return None
        dataframe = pd.read_csv(SAMPLE_DATA_PATH)
        logger.info("Loaded data sample with shape %s", dataframe.shape)
        return dataframe
    except (pd.errors.ParserError, OSError) as exc:
        logger.warning("Failed to load data sample: %s", exc)
        return None


@st.cache_data(show_spinner="Loading model metrics...")
def _load_classification_report() -> Optional[Dict[str, Any]]:
    """
    Load the saved classification report (precision/recall/F1 per class).

    Returns:
        A dictionary parsed from JSON, or None if unavailable/invalid.
    """
    try:
        if not CLASSIFICATION_REPORT_PATH.exists():
            logger.info(
                "Classification report not found at %s", CLASSIFICATION_REPORT_PATH
            )
            return None
        with open(CLASSIFICATION_REPORT_PATH, "r", encoding="utf-8") as file_handle:
            report = json.load(file_handle)
        logger.info("Loaded classification report.")
        return report
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to load classification report: %s", exc)
        return None


@st.cache_data(show_spinner="Loading confusion matrix...")
def _load_confusion_matrix() -> Optional[pd.DataFrame]:
    """
    Load the saved confusion matrix as a labeled DataFrame.

    Expects a CSV where the first column holds true-class labels and
    the remaining columns are predicted-class labels.

    Returns:
        A DataFrame (index = true label, columns = predicted label), or
        None if unavailable/invalid.
    """
    try:
        if not CONFUSION_MATRIX_PATH.exists():
            logger.info("Confusion matrix not found at %s", CONFUSION_MATRIX_PATH)
            return None
        matrix_df = pd.read_csv(CONFUSION_MATRIX_PATH, index_col=0)
        logger.info("Loaded confusion matrix with shape %s", matrix_df.shape)
        return matrix_df
    except (pd.errors.ParserError, OSError) as exc:
        logger.warning("Failed to load confusion matrix: %s", exc)
        return None


@st.cache_data(show_spinner="Loading feature importance...")
def _load_feature_importance() -> Optional[pd.DataFrame]:
    """
    Load feature importance scores produced during model training.

    Returns:
        A DataFrame with 'feature' and 'importance' columns, sorted
        descending by importance, or None if unavailable/invalid.
    """
    try:
        if not FEATURE_IMPORTANCE_PATH.exists():
            logger.info(
                "Feature importance file not found at %s", FEATURE_IMPORTANCE_PATH
            )
            return None
        importance_df = pd.read_csv(FEATURE_IMPORTANCE_PATH)
        if not {"feature", "importance"}.issubset(importance_df.columns):
            logger.warning(
                "Feature importance file missing expected columns: %s",
                importance_df.columns.tolist(),
            )
            return None
        return importance_df.sort_values("importance", ascending=False)
    except (pd.errors.ParserError, OSError) as exc:
        logger.warning("Failed to load feature importance: %s", exc)
        return None


@st.cache_data(show_spinner="Loading model comparison...")
def _load_model_comparison() -> Optional[pd.DataFrame]:
    """
    Load a table comparing multiple trained models' performance.

    Returns:
        A DataFrame of model comparison results, or None if
        unavailable/invalid.
    """
    try:
        if not MODEL_COMPARISON_PATH.exists():
            logger.info(
                "Model comparison file not found at %s", MODEL_COMPARISON_PATH
            )
            return None
        return pd.read_csv(MODEL_COMPARISON_PATH)
    except (pd.errors.ParserError, OSError) as exc:
        logger.warning("Failed to load model comparison: %s", exc)
        return None


def _detect_label_column(dataframe: pd.DataFrame) -> Optional[str]:
    """
    Identify the target/label column within a dataframe.

    Args:
        dataframe: Dataset to inspect.

    Returns:
        The matched column name, or None if no candidate is found.
    """
    for candidate in LABEL_COLUMN_CANDIDATES:
        if candidate in dataframe.columns:
            return candidate
    return None


# --------------------------------------------------------------------------
# Section renderers
# --------------------------------------------------------------------------
def _render_dataset_insights() -> None:
    """Render exploratory dataset visualizations (class balance, distributions)."""
    sample_df = _load_sample_data()

    if sample_df is None:
        st.info(
            "No processed data sample found at "
            f"`{SAMPLE_DATA_PATH}`. Run the preprocessing/EDA pipeline "
            "to enable this section.",
            icon="ℹ️",
        )
        return

    try:
        label_column = _detect_label_column(sample_df)

        if label_column is not None:
            st.markdown("**Class Distribution**")
            class_counts = (
                sample_df[label_column]
                .value_counts()
                .rename_axis("class")
                .reset_index(name="count")
            )
            fig = px.bar(
                class_counts,
                x="class",
                y="count",
                color="class",
                title="Traffic Class Distribution",
            )
            fig.update_layout(showlegend=False)
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.warning(
                "Could not identify a label column in the data sample "
                f"(looked for one of: {LABEL_COLUMN_CANDIDATES})."
            )

        numeric_columns = sample_df.select_dtypes(include="number").columns.tolist()
        if numeric_columns:
            st.markdown("**Feature Distribution Explorer**")
            selected_feature = st.selectbox(
                "Choose a numeric feature to visualize",
                options=numeric_columns,
            )
            hist_fig = px.histogram(
                sample_df,
                x=selected_feature,
                color=label_column if label_column else None,
                marginal="box",
                nbins=50,
                title=f"Distribution of {selected_feature}",
            )
            st.plotly_chart(hist_fig, use_container_width=True)
        else:
            st.warning("No numeric columns available for distribution analysis.")

    except Exception:  # noqa: BLE001
        logger.exception("Failed to render dataset insights.")
        st.error("An error occurred while rendering dataset insights.")


def _render_model_performance() -> None:
    """Render model evaluation visualizations (metrics, confusion matrix, etc.)."""
    try:
        report = _load_classification_report()
        confusion_df = _load_confusion_matrix()
        importance_df = _load_feature_importance()
        comparison_df = _load_model_comparison()

        if not any([report, confusion_df is not None, importance_df is not None, comparison_df is not None]):
            st.info(
                "No model evaluation artifacts found in "
                f"`{METRICS_DIR}`. Run `evaluate_model.py` to generate "
                "them.",
                icon="ℹ️",
            )
            return

        if report is not None:
            st.markdown("**Classification Report**")
            report_df = pd.DataFrame(report).transpose()
            st.dataframe(report_df, use_container_width=True)

        if confusion_df is not None:
            st.markdown("**Confusion Matrix**")
            heatmap_fig = go.Figure(
                data=go.Heatmap(
                    z=confusion_df.values,
                    x=confusion_df.columns.tolist(),
                    y=confusion_df.index.tolist(),
                    colorscale="Blues",
                    text=confusion_df.values,
                    texttemplate="%{text}",
                )
            )
            heatmap_fig.update_layout(
                xaxis_title="Predicted Label",
                yaxis_title="True Label",
                title="Confusion Matrix",
            )
            st.plotly_chart(heatmap_fig, use_container_width=True)

        if importance_df is not None:
            st.markdown("**Top Feature Importances**")
            top_n = min(20, len(importance_df))
            importance_fig = px.bar(
                importance_df.head(top_n),
                x="importance",
                y="feature",
                orientation="h",
                title=f"Top {top_n} Most Important Features",
            )
            importance_fig.update_layout(yaxis={"categoryorder": "total ascending"})
            st.plotly_chart(importance_fig, use_container_width=True)

        if comparison_df is not None:
            st.markdown("**Model Comparison**")
            st.dataframe(comparison_df, use_container_width=True)

    except Exception:  # noqa: BLE001
        logger.exception("Failed to render model performance analytics.")
        st.error("An error occurred while rendering model performance analytics.")


def _render_saved_figures() -> None:
    """Display any pre-rendered static figures saved to reports/figures/."""
    try:
        if not FIGURES_DIR.exists():
            logger.info("Figures directory not found at %s", FIGURES_DIR)
            return

        image_paths: List[Path] = sorted(
            [*FIGURES_DIR.glob("*.png"), *FIGURES_DIR.glob("*.jpg"), *FIGURES_DIR.glob("*.jpeg")]
        )
        if not image_paths:
            return

        st.markdown("**Saved Figures**")
        columns = st.columns(2)
        for index, image_path in enumerate(image_paths):
            target_column = columns[index % 2]
            with target_column:
                st.image(str(image_path), caption=image_path.stem, use_container_width=True)

    except Exception:  # noqa: BLE001
        logger.exception("Failed to render saved figures.")
        st.error("An error occurred while loading saved figures.")


def render() -> None:
    """
    Render the Analytics page.

    This is the public entry point invoked by ``src/dashboard/app.py``.
    All exceptions are caught locally so that a failure on this page
    does not propagate and crash the rest of the dashboard.
    """
    try:
        st.title("📊 Analytics")
        st.markdown(
            "Explore dataset characteristics and trained model performance "
            "for the intrusion detection system."
        )

        tab_dataset, tab_model, tab_figures = st.tabs(
            ["🗃️ Dataset Insights", "🎯 Model Performance", "🖼️ Saved Figures"]
        )

        with tab_dataset:
            _render_dataset_insights()

        with tab_model:
            _render_model_performance()

        with tab_figures:
            _render_saved_figures()

        logger.info("Analytics page rendered successfully.")

    except Exception:  # noqa: BLE001 - page-level safety net
        logger.exception("Unhandled exception while rendering the Analytics page.")
        st.error(
            "An unexpected error occurred while loading the Analytics page. "
            "Please check the application logs for details."
        )